### PR TITLE
Platform GitHub actions

### PR DESCRIPTION
**Pull request by TaylorGarpow**
Do not merge this yet.  This is to look over the entire Actions workflow.  There is a LOT of repeated code needed to filter all of the libraries and then find the one that had changes made to it.

### CODE REVIEW

**Comment by traviswalker26** [comment]
@TaylorGarpow this pattern looks good. Once we know which packages we want to have pipelines for we can refactor this to fit that.

**Comment by TaylorGarpow** [comment]
Up to date. I do not want this to actually run yet, so I have the branch be random name.  When I go to convert the constructs to V2, I will change the name then so it will all run and publish them at the same time

**Review by chrisdettloff — COMMENTED** [review]
It looks good, the pipeline is pretty long. Did you ever consider breaking it up to multiple workflows?

**Comment by TaylorGarpow** [comment]
Yea, but because it is all doing the same thing we wanted to keep it in one workflow.  Once more is done on the Constructs to group them, the workflows will look much better

**Pull request merged**
