### PR TITLE
init for point in time reocvery

### PR DESCRIPTION
**Pull request by TaylorGarpow**

### CODE REVIEW

**Review by traviswalker26 — COMMENTED** [review]
@TaylorGarpow I'm glad you found a property to do this. You should also add a unit test to make sure PITR is configured correctly when that property is true.

**Comment by traviswalker26** [comment]
> Do I need to do something like [THIS](https://stackoverflow.com/questions/70687039/how-to-set-point-in-time-recovery-on-a-dynamodb-replica) instead?

I don't think we need to be concerned with PITR on the replicas right now. We can build that complexity into it later if that becomes a requirement.

**Comment by TaylorGarpow** [comment]
image
Unit test shows configuration for Point-In-Time-Recovery

**Review by traviswalker26 — COMMENTED** [review]
You should have that test in the same file as the other test and also it looks like the assertion doesn't actually assert the PITR configuration in the cloudformation template.

**Pull request closed without merging**
